conky.config = {
    alignment = 'top_left',
    background = false,
    update_interval = 1,
    double_buffer = true,

    own_window = true,
    own_window_type = 'normal',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    minimum_width = 430,
    minimum_height = 820,

    gap_x = 80,
    gap_y = 110,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    use_xft = true,
    font = 'Noto Sans:size=10',

    default_color = 'D8D3CC',
    color1 = 'A93232',
    color2 = '777777',
    color3 = 'F0ECE6',
    color4 = 'A9A39B',

    uppercase = false,
    use_spacer = 'none',

    cpu_avg_samples = 2,
    net_avg_samples = 2,
};

conky.text = [[
${font Noto Serif:size=50}${color3}${time %H:%M}${font Noto Sans:size=11}${color1}  ${time %p}
${voffset -10}${font Noto Serif:size=29}${color1}${time %d/%m}${color2}  ${time %a}

${voffset 28}${font Noto Sans:size=15}${color3}S O R R O W V A L E
${voffset 4}${font Noto Sans:size=8}${color2}FEDORA 44  /  KDE PLASMA
${color2}${execi 60 whoami}@${nodename}


${voffset 17}${font Noto Sans:bold:size=9}${color3}SYSTEM ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color4}CPU${alignr}${color3}${cpu}%
${color1}${cpubar 3}

${voffset 5}${color4}MEMORY${alignr}${color3}${mem} / ${memmax}
${color1}${membar 3}

${voffset 5}${color4}LOAD${alignr}${color3}${loadavg}


${voffset 17}${font Noto Sans:bold:size=9}${color3}THERMALS ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color4}RYZEN 7 2700X${alignr}${color3}${execi 3 sensors | awk '/Tdie:/ {print $2; exit}'}

${voffset 5}${color4}GTX 1660${alignr}${color3}${execi 3 nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits}°C


${voffset 17}${font Noto Sans:bold:size=9}${color3}GRAPHICS ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color4}GPU LOAD${alignr}${color3}${execi 2 nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits}%

${voffset 5}${color4}VRAM${alignr}${color3}${execi 2 nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits} MiB / 6144 MiB

${voffset 5}${color4}FAN${alignr}${color3}${execi 2 nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits}

${voffset 5}${color4}POWER${alignr}${color3}${execi 2 nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits} W


${voffset 17}${font Noto Sans:bold:size=9}${color3}STORAGE ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color4}ROOT${alignr}${color3}${fs_used /} / ${fs_size /}
${color1}${fs_bar 3 /}


${voffset 17}${font Noto Sans:bold:size=9}${color3}NETWORK ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color4}DOWN${alignr}${color3}${downspeed} 
${voffset 4}${color4}UP${alignr}${color3}${upspeed}


${voffset 17}${font Noto Sans:bold:size=9}${color3}UPTIME ${color1}${hr 1}

${voffset 7}${font Noto Sans:size=9}${color3}${uptime}
]];
